In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
data = pd.read_csv('Data Visualization Scoring Sheet FS25(1-337).csv') # Import Forms File
data = data[data["What section are you in?\n"] == "001: Robert Termuhlen"] # Change to your section!
data.head()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your first and last name?,What section are you in?\n,What group are you scoring here?\n,How well did the group's plot convey its story in comparison with your initial thoughts? (1=poorly - 8=perfectly)\n,"How well did the group manage to keep wasted space to a minimum? (1=poorly, 3=perfectly)\n","How well is the data context articulated? (1=none given, 5=very well articulated)\n","How descriptive were the labels/legend/title? How well did the group do in emphasizing the plot over the text? (1=poorly, 2=well)","Bonus: Did their plot display multiple variables (3 or more)? (1=no, 2=yes)\n"
0,1,11/5/25 9:19:10,11/5/25 9:20:55,maurer17@msu.edu,Jacob Maurer,NaN,Jacob Maurer,001: Robert Termuhlen,Group 10,5,3,3,2,1
1,2,11/5/25 9:18:21,11/5/25 9:21:21,swamyani@msu.edu,swamyani@msu.edu,NaN,Ani Swamy,001: Robert Termuhlen,Group 10,6,3,4,2,1
2,3,11/5/25 9:17:48,11/5/25 9:21:50,espin171@msu.edu,Lorena Espinosa Gomez,NaN,Lorena Espinosa,001: Robert Termuhlen,Group 10,5,2,3,2,1
3,4,11/5/25 9:18:31,11/5/25 9:22:35,cialonee@msu.edu,Elliott Cialone,NaN,Elliott Cialone,001: Robert Termuhlen,Group 10,6,3,3,1,1
4,5,11/5/25 9:18:02,11/5/25 9:22:41,chittan1@msu.edu,Anwith Chittanuri,NaN,Anwith Balakrishna Chittanuri,001: Robert Termuhlen,Group 10,6,2,4,2,1

In [12]:
cols = data.columns[9:14] 
data['score'] = data[cols].sum(axis=1, numeric_only=True)/(8+3+4)

data2 = data.groupby('What group are you scoring here?\n')[['score']].mean()
data2.sort_values('score', ascending=False)

                                       score
What group are you scoring here?\n
Group 2                             1.190000
Group 5                             1.123810
Group 8                             1.117117
Group 7                             1.115315
Group 6                             1.095935
Group 4                             1.084444
Group 3                             1.078095
Group 10                            1.072917
Group 9                             0.894737
Group 1                             0.889474